version: '3'
networks:
  superset-demo-net:
    driver: bridge
volumes:
  postgres-data:
    driver: local
services:

  # ------ MongoDB ------
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MyUser
      - MONGO_INITDB_ROOT_PASSWORD=MyCredential
    networks:
      - superset-demo-net
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD-SHELL", "echo test" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------ PostgreSQL ------

  postgres:
    container_name: postgres_db_dw
    image: postgres
    environment:
      POSTGRES_USER: dev-ninja
      POSTGRES_PASSWORD: ujac8ozJExiHFfcTNPd6
      POSTGRES_DB: postgres_db_dw
    ports:
      - "5432:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'
    networks:
      - superset-demo-net
    restart: always

  # ------ Spring Services ------

  # ------ mongodb-csv-data-warehouse ------
  mongodb-csv-data-warehouse:
    container_name: mongodb-csv-data-warehouse
    build:
      context: mongodb-csv-datawarehouse
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://MyUser:MyCredential@mongodb:27017/reactive_events_v2?authSource=admin
    networks:
      - superset-demo-net
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy

  # ------ postgresql-etl-scheduler ------
#  postgresql-etl-scheduler:
#    container_name: postgresql-etl-scheduler
#    build:
#      context: mongodb-csv-datawarehouse
#      dockerfile: Dockerfile
#    environment:
#      - MONGODB_CONNECTION_STRING=mongodb://MyUser:MyCredential@mongodb:27017/reactive_events_v2?authSource=admin
#      - POSTGRES_CONNECTION_STRING=jdbc:postgresql://postgres_db_dw:5432/postgres_db_dw
#      - POSTGRES_USER=dev-ninja
#      - POSTGRES_PASSWORD=ujac8ozJExiHFfcTNPd6
#    networks:
#      - superset-demo-net
#    ports:
#      - "8081:8081"
#    depends_on:
#      topic-starter:
#        condition: service_healthy